### ISSUE TITLE
Order of calls to (SETF FDEFINITION) and FUNCTION-CELL makes a difference to final result.

### ISSUE THREAD

**Issue by robert-strandh** [s-expressionists/Clostrum#3]
If I call (SETF FDEFINITION) and then FUNCTION-CELL, then the CAR of the function cell I receive 
contains the definition I supplied:

(setf (env:fdefinition (env:client *e2*) *e2* 'hello) (lambda (x) 234)

(defparameter *c* (env:function-cell (env:client *e2*) *e2* 'hello)

(funcall (car *c*) 'a) => 234

But if I do it the other way around, the cell does not get modified:

(defparameter *d* (env:function-cell (env:client *e2*) *e2* 'hithere))

(setf (env:fdefinition (env:client *e2*) *e2* 'hithere) (lambda (x) 333))

(funcall (car *d*) 'a) => error: undefined function

**Comment by robert-strandh** [comment]
I think I see what is going on.  The cell is created only as a result of
calling FUNCTION-CELL, and then it is initialized from the function
definition (if it exists) which is stored elsewhere.  But when the
function definition is updated (or supplied) later by a call to 
(SETF FDEFINITIION), the cell is not updated.  The best solution
I think is to store the function only in one place, namely the CAR of the
cell.  There is no point in having it in a second place.  In other words,
(SETF FDEFINITION) should be defined as (SETF (CAR (FUNCTION-CELL ...)) ...).

**Comment by robert-strandh** [comment]
Similarly, FMAKUNBOUND should set the CAR of the function cell to the UNBOUND value.

**Comment by dkochmanski** [comment]
the operator function-cell has been removed from the specification ("virtual" implementation is still based on cells and the problem is fixed there).
